config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'
  # get 'password_resets/edit'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/opportunities', to: 'appointments#index'
  get '/signup',   to: 'users#new'
  root 'public#home'

  # get 'public/home'

  get 'public/help'
  get 'public/feedback'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :appointments,        only: [:new, :show, :create, :edit, :update, :destroy] do
    collection do
      put :accept_applicants
    end
  end
  resources :appointment_applications
  resources :reviews

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :category

  has_many :applicants, class_name: "AppointmentApplication",
           foreign_key: "appointment_id",
           dependent: :destroy

  has_many :pending_applicants, -> { where status:1 } ,class_name: "AppointmentApplication",
           foreign_key: "appointment_id",
           dependent: :destroy

  has_many :approve_applicants, -> { where status:2 } ,class_name: "AppointmentApplication",
           foreign_key: "appointment_id",
           dependent: :destroy

  has_many :reject_applicants, -> { where status:3 } ,class_name: "AppointmentApplication",
           foreign_key: "appointment_id",
           dependent: :destroy

  has_many :cancel_applicants, -> { where status:4 } ,class_name: "AppointmentApplication",
           foreign_key: "appointment_id",
           dependent: :destroy

  # has_many :pending_applicants, through: :pending, source: :pending_appointment

  has_many :appointment_sessions, inverse_of: :appointment
  accepts_nested_attributes_for :appointment_sessions, allow_destroy: true,
                                reject_if: :all_blank

  validates :category_id, presence: true
  validates :city_id, presence: true
  validates :pax, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :location, presence: true

  def is_open?
    status_name(status) == "Open" ? true : false
  end

  def is_progress?
    status_name(status) == "Progress" ? true : false
  end

  def is_completed?
    status_name(status) == "Completed" ? true : false
  end

  def is_closed?
    status_name(status) == "Closed" ? true : false
  end

  def status_name(status)
    case status.to_s
      when "0"
        return "Open"
      when "1"
        return "Progress"
      when "2"
        return "Completed"
      when "3"
        return "Closed"
    end
  end

  def applicant_include?(user)
    !applicants.find_by(user_id: user.id, status: 1).nil?
  end

  def update_status_to_progress
    update_attribute(:status, 1)
  end

  def appointment_owner?(current_user)
    user_id == current_user.id
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :employer?, only: [:new, :create]
  before_action :logged_in_user
  before_action :is_owner?, only: [:edit, :update, :accept_applicants, :reject_applicants]
  after_action :check_pax, only: [:accept_applicants]

  @@appointment_owner_message = "Only appointment owner can perform this action."
  @@employer_only_message = "Only employer are allow to perform this action."
  @@unable_to_update = "Only employer are allow to perform this action."

  def new
    @appointment = Appointment.new
    @appointment.city_id = current_user.city.id
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash[:info] = "Appointment created."
      redirect_to @appointment
    else
      render 'new'
    end
  end

  def index
    @appointments = Appointment.all
    # @appointments = current_user.opportunities(current_user.category_ids, current_user.city_id)
    @running_app = current_user.progress_appointment(current_user)
    @completed_app = current_user.completed_appointment(current_user)
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update_attributes(appointment_params)
      # Handle a successful update.
      flash[:success] = "Appointment updated"
      redirect_to @appointment
    else
      render 'edit'
    end
  end

  def destroy

  end

  def accept_applicants
    AppointmentApplication.where('id IN (?)', params[:applicant_ids]).update_all(status: 2)
    flash[:success] = "Applicants accepted!"

    @appointment = Appointment.find(params[:appointment_id])
    redirect_to appointment_path(@appointment)
  end

  def reject_applicants
    AppointmentApplication.where('id IN (?)', params[:applicant_ids]).update_all(status: 3)
    flash[:success] = "Applicants rejected!"

    @appointment = Appointment.find(params[:appointment_id])
    redirect_to appointment_path(@appointment)
  end

  private
  def appointment_params
    # params.require(:appointment).permit!
    params.require(:appointment).permit(:user_id, :category_id, :city_id,
                                        :pax, :title, :description, :address,
                                        :location, :status,
                                        appointment_sessions_attributes: [:id, :time, :_destroy])
  end

  def is_owner?
    appointment = Appointment.find(params[:appointment_id] || params[:id])
    flash[:danger] = @@appointment_owner_message and redirect_to appointment unless appointment.appointment_owner?(current_user)
  end

  def check_pax
    appointment = Appointment.find(params[:appointment_id])
    if appointment.pax == appointment.approve_applicants.count
      appointment.update_status_to_progress
    end
  end

  def employer?
    flash[:danger] = @@employer_only_message and redirect_to opportunities_path unless current_user.is_employer?
    # redirect_to opportunities_path
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<div class="appointment_index shadow">
    <div class="title-column"><%= appointment.title %></div>
    <div class="title-detail-change">
      <%= link_to appointment_path(appointment) do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
    </div>

  <div style="clear:both">
    <div class="appointment_body_into_half">
      <div class="display_table">
        <div>Employer :</div>
        <div><%= appointment.user.fullname if appointment.user %></div>
      </div>
      <div class="display_table">
        <div>Category :</div>
        <div><%= appointment.category.name if appointment.category %></div>
      </div>
    </div>
    <div class="appointment_body_into_half">
      <div class="display_table">
        <div>City :</div>
        <div><%= appointment.city.name if appointment.city %></div>
      </div>
      <div class="display_table">
        <div>Pax :</div>
        <div>0 / <%= appointment.pax if appointment.pax %></div>
      </div>
    </div>

    <div class="appointment_sessions_index">
      <% appointment.appointment_sessions.each_with_index do |app_session, index| %>
        <div class="display_table">
          <div>Available Time <%= index + 1 %> :</div>
          <div><%= app_session.time.strftime('%Y-%m-%d (%I:%M %P)') %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appointments/_appointment_applicants.html.erb
<% unless @appointment.pending_applicants.count == 0 %>
  <% if @appointment.user_id == current_user.id %>
    <h3>Pending applicants</h3>
    <%= form_tag accept_applicants_appointments_path, method: :put,
                 data: {confirm: "You sure? This action can't be redo."} do %>
      <%= hidden_field_tag :appointment_id, @appointment.id %>
      <table class="table table-bordered">
        <thead>
        <tr>
          <th></th>
          <th>No</th>
          <th>Applicant's Name</th>
          <th>Applicant's Rating</th>
          <th>Message</th>
        </tr>
        </thead>
        <tbody>
        <% @appointment.pending_applicants.each_with_index do |applicant, index| %>
          <tr>
            <td><%= check_box_tag "applicant_ids[]", applicant.id %></td>
            <td><%= index + 1 %></td>
            <td><%= link_to applicant.user.fullname, applicant.user %></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <%= submit_tag "Accept chosen applicant(s)", class: "btn btn-danger" %>
    <% end %>
  <% end %>
<% end %>

<% unless @appointment.reject_applicants.count == 0 %>
  <% if @appointment.user_id == current_user.id %>
    <h3>Rejected Applicants</h3>
    <%= form_tag accept_applicants_appointments_path, method: :put do %>
      <%= hidden_field_tag :appointment_id, @appointment.id %>
      <table class="table table-bordered">
        <thead>
        <tr>
          <th></th>
          <th>No</th>
          <th>Applicant's Name</th>
          <th>Applicant's Rating</th>
          <th>Message</th>
        </tr>
        </thead>
        <tbody>
        <% @appointment.reject_applicants.each_with_index do |applicant, index| %>
          <tr>
            <td><%= check_box_tag "applicant_ids[]", applicant.id %></td>
            <td><%= index + 1 %></td>
            <td><%= link_to applicant.user.fullname, applicant.user %></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <%= submit_tag "Accept chosen applicant(s)", class: "btn btn-danger" %>
    <% end %>
  <% end %>
<% end %>

<% unless @appointment.cancel_applicants.count == 0 %>
  <% if @appointment.user_id == current_user.id %>
    <h3>Cancelled Applicants</h3>
    <%= form_tag accept_applicants_appointments_path, method: :put do %>
      <%= hidden_field_tag :appointment_id, @appointment.id %>
      <table class="table table-bordered">
        <thead>
        <tr>
          <th></th>
          <th>No</th>
          <th>Applicant's Name</th>
          <th>Applicant's Rating</th>
          <th>Message</th>
        </tr>
        </thead>
        <tbody>
        <% @appointment.cancel_applicants.each_with_index do |applicant, index| %>
          <tr>
            <td><%= check_box_tag "applicant_ids[]", applicant.id %></td>
            <td><%= index + 1 %></td>
            <td><%= link_to applicant.user.fullname, applicant.user %></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <%= submit_tag "Accept chosen applicant(s)", class: "btn btn-danger" %>
    <% end %>
  <% end %>
<% end %>

app/views/appointments/_appointment_session.html.erb
<tr class="nested-fields">
  <td><%= f.datetime_field :time, label: false %></td>
  <!--<td><%= f.datetime_field :time, label: false, min: DateTime.now.strftime('%Y-%m-%dT%H:%M') %></td>-->
  <td><%= link_to_remove_association "remove task", f, class: 'btn btn-primary btn-xs' %></td>
</tr>

app/views/appointments/_cancel_request.html.erb
<%= form_for(@appointment.applicants.find_by(user_id: current_user.id),
             html: { method: :patch }) do |f| %>

  <div><%= hidden_field_tag :appointment_id, @appointment.id %></div>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <div><%= hidden_field_tag :status, 4 %></div>

  <%= f.submit "Cancel Request", class: "btn btn-warning" %>
<% end %>

app/views/appointments/_completed_appointment.html.erb
<% @completed_app.each do |appointment| %>
  <div class="appointment_index shadow">
    <div class="title-column"><%= appointment.title %></div>
    <div class="title-detail-change">
      <%= link_to appointment_path(appointment) do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
    </div>

    <div style="clear:both">
      <div class="appointment_body_into_half">
        <div class="display_table">
          <div>Employer :</div>
          <div><%= appointment.user.fullname if appointment.user %></div>
        </div>
        <div class="display_table">
          <div>Category :</div>
          <div><%= appointment.category.name if appointment.category %></div>
        </div>
      </div>
      <div class="appointment_body_into_half">
        <div class="display_table">
          <div>City :</div>
          <div><%= appointment.city.name if appointment.city %></div>
        </div>
        <div class="display_table">
          <div>Pax :</div>
          <div>0 / <%= appointment.pax if appointment.pax %></div>
        </div>
      </div>

      <div class="appointment_sessions_index">
        <% appointment.appointment_sessions.each_with_index do |app_session, index| %>
          <div class="display_table">
            <div>Available Time <%= index + 1 %> :</div>
            <div><%= app_session.time.strftime('%Y-%m-%d (%I:%M %P)') %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/appointments/_confirmed_applicants.html.erb
<% unless @appointment.approve_applicants.count == 0 %>
  <% if @appointment.is_completed? %>
    <h3>Rating Applicants</h3>
  <% else %>
    <h3>Confirmed Applicants</h3>
  <% end %>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th>No</th>
      <th>Applicant's Name</th>
      <% if @appointment.is_completed? %>
        <th>Performance Rating</th>
        <th>Comments</th>
      <% else %>
        <th>Applicant's Rating</th>
        <th>Message</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @appointment.approve_applicants.each_with_index do |applicant, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= link_to applicant.user.fullname, applicant.user %></td>
        <% if @appointment.is_completed? %>
          <% if applicant.review.nil? %>
            <td><%= link_to "Reviews", applicant.build_review, "data-toggle" => "modal", "data-target" => "#detail#{applicant.id}" %></td>
            <td></td>

            <!--Modal-->
            <div class="modal fade" id="detail<%= applicant.id %>" role="dialog">
              <div class="modal-dialog">
                <!--Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close close_book_detail" data-dismiss="modal">&times;</button>
                    <%= form_for(applicant.build_review) do |f| %>
                      <%= render 'shared/error_messages', object: f.object %>

                      <%= hidden_field_tag :appointment_id, @appointment.id %>

                      <%= f.hidden_field :review_by, value: current_user.id %>
                      <%= f.hidden_field :user_id, value: applicant.user.id %>
                      <%= f.hidden_field :appointment_application_id, value: applicant.id %>

                      Rating for user <%= applicant.user.fullname %>

                      <div class="form-group row">
                        <%= f.label :rating, class: 'col-sm-2 form-control-label' %>
                        <div class="col-sm-6" id='star-rating'>
                          <%=hidden_field_tag "review[rating]", '', id: "rating_star" %>
                        </div>
                      </div>

                      <%= f.label :comment %>
                      <%= f.text_area :comment, placeholder: "Please enter comment here." %>

                      <%= f.submit "Save changes", class: "btn btn-primary" %>
                    <% end %>
                  </div>

                </div>
              </div>
            </div>
          <% else %>
            <td><div class="star-rating-show" data-score= <%= applicant.review.rating %> ></div></td>
            <td><%= applicant.review.comment %></td>
          <% end %>
        <% else %>
          <td></td>
          <td></td>
        <% end %>

      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<script>
    $(document).on('turbolinks:load', function() {
        $('#star-rating').raty({
            path: '/assets',
            target: '#rating_star',
            targetType: 'score',
            targetKeep: true
        });
    });
</script>




<script>
    $(document).on('turbolinks:load', function() {
      $('.star-rating-show').raty({
          path: '/assets/',
          readOnly: true,
          score: function() {
              return $(this).attr('data-score');
          }
      });
    });
</script>

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :city_id %>
  <%= f.collection_select :city_id, City.all, :id, :name, {prompt: "Select a city"}, {class: "form-control"} %>

  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, {class: "form-control"} %>

  <%= f.label :pax %>
  <%= f.number_field :pax, default: 1, min: 1, class: 'form-control' %>

  <%= f.label :address %>
  <%= f.text_area :address, class: 'form-control' %>

  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <h3>Sessions</h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Available Time</th>
        <th><%= link_to_add_association 'Add Sessions', f, :appointment_sessions,
                                        partial: 'appointment_session', class: 'btn btn-danger',
                                        data: { association_insertion_node: '.appointment_sessions', association_insertion_method: :append } %></th>
      </tr>
    </thead>
    <tbody class="appointment_sessions">
      <%= f.fields_for :appointment_sessions do |app_session| %>
        <%= render 'appointment_session', :f => app_session %>
      <% end %>
    </tbody>
  </table>

  <%= f.submit "Save changes", class: "btn btn-danger" %>
<% end %>

app/views/appointments/_request.html.erb
<%= form_for(current_user.appointment_applicant.build) do |f| %>
  <div><%= hidden_field_tag :appointment_id, @appointment.id %></div>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <%= f.submit "Send Request", class: "btn btn-info" %>
<% end %>

app/views/appointments/_request_form.html.erb
<% if @appointment.is_open? && !current_user.is_employer? %>
<div id="request_form">
  <% if @appointment.applicant_include?(current_user) %>
    <%= render 'cancel_request' %>
  <% else %>
    <%= render 'request' %>
  <% end %>
</div>
<% end %>

app/views/appointments/_running_app.html.erb
<% @running_app.each do |appointment| %>
  <div class="appointment_index shadow">
    <div class="title-column"><%= appointment.title %></div>
    <div class="title-detail-change">
      <%= link_to appointment_path(appointment) do %>
        <i class="glyphicon glyphicon-eye-open"></i>
      <% end %>
    </div>

    <div style="clear:both">
      <div class="appointment_body_into_half">
        <div class="display_table">
          <div>Employer :</div>
          <div><%= appointment.user.fullname if appointment.user %></div>
        </div>
        <div class="display_table">
          <div>Category :</div>
          <div><%= appointment.category.name if appointment.category %></div>
        </div>
      </div>
      <div class="appointment_body_into_half">
        <div class="display_table">
          <div>City :</div>
          <div><%= appointment.city.name if appointment.city %></div>
        </div>
        <div class="display_table">
          <div>Pax :</div>
          <div>0 / <%= appointment.pax if appointment.pax %></div>
        </div>
      </div>

      <div class="appointment_sessions_index">
        <% appointment.appointment_sessions.each_with_index do |app_session, index| %>
          <div class="display_table">
            <div>Available Time <%= index + 1 %> :</div>
            <div><%= app_session.time.strftime('%Y-%m-%d (%I:%M %P)') %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<% provide(:title, "Edit Appointment") %>
<h1>Update your Appointment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/appointments/index.html.erb
<% provide(:title, 'Opportunities') %>

<div class="row form-group opportunities">
  <div class="col-xs-12">
    <ul class="nav nav-pills nav-justified thumbnail appointment_index_nav_bar">
      <li class="active"><a href="#opportunities">
        <h4 class="list-group-item-heading">Opportunities</h4>
      </a></li>
      <li><a href="#running">
        <h4 class="list-group-item-heading">Progressing</h4>
      </a></li>
      <li><a href="#completed">
        <h4 class="list-group-item-heading">Completed</h4>
      </a></li>
    </ul>
  </div>
</div>

<!--<h1>Opportunities</h1>-->

<div class="row appointment_content" id="opportunities">
  <div class="col-xs-12">
    <div class="col-md-12 well">
        <%= render @appointments %>
    </div>
  </div>
</div>
<div class="row appointment_content" id="running">
  <div class="col-xs-12">
    <div class="col-md-12 well">
      <% if @running_app.any? %>
         <%= render 'running_app' %>
      <% else %>
        <h1 class="text-center">There is no any running appointment.</h1>
      <% end %>
    </div>
  </div>
</div>
<div class="row appointment_content" id="completed">
  <div class="col-xs-12">
    <div class="col-md-12 well">
      <% if @completed_app.any? %>
        <%= render 'completed_appointment' %>
      <% else %>
        <h1 class="text-center">There is no any running appointment.</h1>
      <% end %>
    </div>
  </div>
</div>


app/views/appointments/new.html.erb
<% provide(:title, 'Create Appointment') %>
<h1>Create Appointment</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/appointments/show.html.erb
<%= provide(:title, @appointment.title) %>

<h1><%= @appointment.title %></h1>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked admin-menu">
          <li class="active"><a href="#" data-target-id="basic_info"><i class="fa fa-home fa-fw"></i>Basic Info</a></li>
          <li><a href="#" data-target-id="pictures"><i class="fa fa-list-alt fa-fw"></i>Pictures</a></li>
          <li>
            <a href="#" data-target-id="applicants"><i class="glyphicon glyphicon-user"></i> &nbsp; | &nbsp; Applicants</a>
          </li>
          <li>
            <a href="#" data-target-id="confirmed_applicants"><i class="glyphicon glyphicon-user"></i> &nbsp; | &nbsp; Confirmed Applicants</a>
          </li>
          <li><a href="#" data-target-id="freelancers"><i class="fa fa-list-alt fa-fw"></i>Get Freelancers</a></li>
        </ul>

        <br/>
        <% if @appointment.is_open? %>
        <center>
          <%= link_to edit_appointment_path(@appointment) do %>
            <button class="btn btn-danger">Edit <i class="glyphicon glyphicon-pencil"></i></button>
          <% end %>
        </center>
        <% end %>

        <% if @appointment.is_progress? %>
          <%= form_for @appointment,
                       html: { method: :patch } do |f| %>

            <%= f.hidden_field :id, value: @appointment.id %>
            <%= f.hidden_field :status, value: 2 %>

            <%= f.submit "Close Appointment", class: "btn btn-warning" %>
          <% end %>

        <% end %>

      </div>
      <div class="col-md-9 admin-content" id="basic_info">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><label for="new_password" class="control-label panel-title">Basic Info</label></h3>
          </div>
          <div class="panel-body">
            <%= @appointment.title %> <br/>
            <%= @appointment.user.fullname %> <br/>
            <%= @appointment.category.name %> <br/>
            <%= @appointment.city.name %> <br/>
            <%= @appointment.pax %> pax<br/>
            <%= @appointment.description %> <br/>
            <%= @appointment.status_name(@appointment.status) %> <br/>
            <%= @appointment.address %> <br/>
            <%= @appointment.location %> <br/>

            Available Time : <br/>
            <% if @appointment.appointment_sessions %>
              <% @appointment.appointment_sessions.each_with_index do |app_session, index| %>
                <%= index + 1 %>
                Time : <%= app_session.time.strftime('%Y-%m-%d (%I:%M %P)') %> <br/>
              <% end %>
            <% end %>

            <%= render 'request_form' %>
          </div>
        </div>
      </div>

      <div class="col-md-9 well admin-content" id="pictures">
      </div>

      <div class="col-md-9 admin-content" id="applicants">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><label for="new_password" class="control-label panel-title">Applicants Info</label>
            </h3>
          </div>
          <div class="panel-body">
            <%= render 'appointment_applicants' %>
          </div>
        </div>
      </div>

      <div class="col-md-9 admin-content" id="confirmed_applicants">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><label for="new_password" class="control-label panel-title">Applicants Info</label>
            </h3>
          </div>
          <div class="panel-body">
            <%= render 'confirmed_applicants' %>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>